[package]
name = "cql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.1"
csv = "1.1.6"
prettytable-rs = "^0.8"
clap = { version = "3.2.7", features = ["derive"] }
